import type { Metadata } from "next";
import { Ubuntu_Sans } from "next/font/google";
import "./globals.css";
import ClientProviders from "./Provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sooner";




const ubuntuSans = Ubuntu_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn("min-h-screen bg-background font-sans antialiased", ubuntuSans.className)}
      >
        <ClientProviders>
          {children}
        </ClientProviders>
        <Toaster/>
      </body>
    </html>
  );
}
